# Generated by Django 3.1 on 2022-04-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='is_simplified',
            field=models.BooleanField(default=False),
        ),
    ]
