# Generated by Django 3.1 on 2022-04-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapedbody',
            name='website',
        ),
        migrations.AddField(
            model_name='website',
            name='is_new_data_collected',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='AccountType',
        ),
        migrations.DeleteModel(
            name='ScrapedBody',
        ),
    ]
