# Generated by Django 3.1 on 2022-04-08 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0002_website_is_simplified'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
