# Generated by Django 3.1 on 2022-03-12 18:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0003_auto_20220312_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='test',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
